### ISSUE TITLE
Theme manager loads then traceback error

### ISSUE THREAD

**Issue by Noidea24** [V0r-T3x/fancygotchi#8]
Running xbits/jayofelony's pwnagotchi-torch 2.5.6.
RPi Zero with waveshare 1.3" LCD hat.
Start with display working fine, no rotation enabled, "lcdhat" display type, ui enabled.
Specified custom plugin folder, copied fancygotchi.py and the fancygotchis folder to the specified plugin folder.
Added the following lines to config.toml

> main.plugins.fancygotchi.enabled = false
main.plugins.fancygotchi.theme = '' 
main.plugins.fancygotchi.rotation = 0

Rebooted, accessed web ui, enabled fancygotchi, refreshed the page, no connection. display on the rpi freezes.
Command "systemctl status pwnagotchi" returns that the pwnagotchi launcher has errored and exited.
Command "sudo /usr/bin/pwnagotchi-launcher" outputs the following.... 

> /usr/bin/pwnlib: line 7: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 9: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 7: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 9: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 7: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 9: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 7: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 9: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 7: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 9: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 7: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 9: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 7: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 9: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 7: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 9: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 7: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 9: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 7: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 9: /sys/class/leds/led0/brightness: No such file or directory
/usr/bin/pwnlib: line 12: /sys/class/leds/led0/brightness: No such file or directory
[2023-12-01 01:24:42,189] [INFO] webcfg: Plugin loaded.
[2023-12-01 01:24:42,200] [INFO] [update] plugin loaded.
[2023-12-01 01:24:42,197] [INFO] grid plugin loaded.
[2023-12-01 01:24:42,196] [INFO] [FANCYGOTCHI] Beginning Fancygotchi load
[2023-12-01 01:24:42,191] [INFO] [Fix_Services] plugin loaded.
[2023-12-01 01:24:42,201] [INFO] Session-stats plugin loaded.
[2023-12-01 01:24:42,318] [INFO] Lines already exist. No changes needed.
[2023-12-01 01:24:42,351] [INFO] [FANCYGOTCHI] Theme manager loaded
[2023-12-01 01:24:42,460] [INFO] BT-TETHER: Successfully loaded ...
[2023-12-01 01:24:42,584] [WARNING] got here
Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 206, in <module>
    display = Display(config=config, state={'name': '%s>' % pwnagotchi.name()})
  File "/usr/local/lib/python3.9/dist-packages/pwnagotchi/ui/display.py", line 12, in __init__
    super(Display, self).__init__(config, hw.display_for(config), state)
  File "/usr/local/lib/python3.9/dist-packages/pwnagotchi/ui/view.py", line 201, in __init__
    'face': Text(value=faces.SLEEP, position=th_face['position'], color=th_face['color'], font=getattr(fonts, th_face['font']), face=True),
  File "/usr/local/lib/python3.9/dist-packages/pwnagotchi/ui/components.py", line 163, in __init__
    th_img_t = th['face']['image_type']
KeyError: 'image_type'

At this point i can disable the plugin by editing the configs.toml custom plugin location to an empty folder, restart pwnagotchi, and everything loads up

**Comment by Noidea24** [comment]
Sorry, i found the solution. After the crash, i edited config.toml to specify a theme. after specifying a theme in the config, everything booted up fine.
